apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: texlive-runboy
spec:
  repository: brandoneto/resume
  image: ghcr.io/brandoneto/runner-x:20220916.1
  imagePullPolicy: IfNotPresent
  dockerEnabled: false
  ephemeral: false
  labels:
    - texlive
  env: []
