name: testing rn

on:
  workflow_call:
  workflow_dispatch:

jobs:
  working:
    runs-on: ubuntu-latest
    steps: 
      - run: pwd
  desorty-step:
    uses: ./.github/workflows/destory.yml
    secrets: inherit