name: 'Terraform Nuke'

on: 
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  plan:
    strategy: 
      matrix: 
        env: [sandbox]
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        # working-directory: terraform-resume/aks-simple

    steps:
    - name: Checkout
      uses: actions/checkout@v3
        with: 
          repository: brandoneto/terraform-resume
          
    - run: |
        echo $GITHUB_WORKSPACE
        ls -l /home/runner/work
        cd /home/runner/work/resume
        ls -l
        cd /home/runner/work/resume/resume
        ls -l

    - name: Terraform Destroy
      run: |
        terraform init -backend-config=key=${{ matrix.env  }}.tfvars
        terraform destroy -auto-approve -var-file=env/${{ matrix.env  }}.tfvars
    